const itemDetails = {
  item1: {
    id: "1",
    name: "Organic Hass Avocado",
    image: "/images/avocado.png",
    quantity: "2",
    price: "$15",
  },
  item2: {
    id: "2",
    name: "Frash watermelon",
    image: "/images/watermelon.png",
    quantity: "4",
    price: "$15.99",
  },
  item3: {
    id: "3",
    name: "Strawberry",
    image: "/images/strawberry.png",
    quantity: "7",
    price: "$17.99",
  },
  item4: {
    id: "4",
    name: "Tomato",
    image: "/images/tomato.png",
    quantity: "17",
    price: "$3",
  },
  item5: {
    id: "5",
    name: "Orange",
    image: "/images/orange.png",
    quantity: "22",
    price: "$7",
  },
  item6: {
    id: "6",
    name: "Organic Hass Avocado",
    image: "/images/avocado.png",
    quantity: "2",
    price: "$15",
  },
  item7: {
    id: "7",
    name: "Frash watermelon",
    image: "/images/watermelon.png",
    quantity: "4",
    price: "$15.99",
  },
  item8: {
    id: "8",
    name: "Strawberry",
    image: "/images/strawberry.png",
    quantity: "7",
    price: "$17.99",
  },
  item9: {
    id: "9",
    name: "Tomato",
    image: "/images/tomato.png",
    quantity: "17",
    price: "$3",
  },
  item10: {
    id: "10",
    name: "Orange",
    image: "/images/orange.png",
    quantity: "22",
    price: "$7",
  },
  item11: {
    id: "11",
    name: "Organic Hass Avocado",
    image: "/images/avocado.png",
    quantity: "2",
    price: "$15",
  },
  item12: {
    id: "12",
    name: "Frash watermelon",
    image: "/images/watermelon.png",
    quantity: "4",
    price: "$15.99",
  },
  item13: {
    id: "13",
    name: "Strawberry",
    image: "/images/strawberry.png",
    quantity: "7",
    price: "$17.99",
  },
  item14: {
    id: "14",
    name: "Tomato",
    image: "/images/tomato.png",
    quantity: "17",
    price: "$3",
  },
  item15: {
    id: "15",
    name: "Orange",
    image: "/images/orange.png",
    quantity: "22",
    price: "$7",
  },
};

export default itemDetails;
